name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: 
  push:
    branches:
      - 'add_gitAction_demo'
  workflow_dispatch:
    inputs:
      who-to-greet: # id of input
        description: 'Who to greet'
        required: true
        default: 'World'
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "ğŸ‰ ğŸ‰ ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "ğŸ‘‹ Hello, ${{ github.event.inputs.who-to-greet }}!"
#       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "ğŸ This job's status is ${{ job.status }}."
jobs:
  predefined_variables:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: "Hello, World!"
      ANOTHER_VARIABLE: "123"

    steps:
    - name: Display Predefined Variables
      run: |
        echo "MY_VARIABLE: $MY_VARIABLE"
        echo "ANOTHER_VARIABLE: $ANOTHER_VARIABLE"

    - name: Use Predefined Variables in a Command
      run: |
        echo "Using MY_VARIABLE in a command: $MY_VARIABLE"

    - name: Use Predefined Variables in a Script
      run: |
        echo "Using ANOTHER_VARIABLE in a script: $ANOTHER_VARIABLE" 

    - name: greeting!!!
      run: | 
      echo "ğŸ‘‹ Hello, $who-to-greet"

    # - run: echo "ğŸ‰ ğŸ‰ ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    # - run: echo "ğŸ‘‹ Hello, ${{ inputs.who-to-greet }}!"
    # - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    # - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    # - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    # - name: Check out repository code
    #   uses: actions/checkout@v4
    # - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
   
    - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: echo "ğŸ This job's status is ${{ job.status }}."
# jobs: